In [19]:
import pandas as pd
import numpy as np
import sklearn
import matplotlib.pyplot as plt

In [8]:
import tensorflow as tf

In [3]:
print("hey")

hey


In [27]:
df = pd.read_csv("../input/train.csv")
df.head()

id  bin_0  bin_1  bin_2 bin_3 bin_4 nom_0      nom_1    nom_2       nom_3  \
0   0    0.0    0.0    0.0     F     N   Red  Trapezoid  Hamster      Russia   
1   1    1.0    1.0    0.0     F     Y   Red       Star  Axolotl         NaN   
2   2    0.0    1.0    0.0     F     N   Red        NaN  Hamster      Canada   
3   3    NaN    0.0    0.0     F     N   Red     Circle  Hamster     Finland   
4   4    0.0    NaN    0.0     T     N   Red   Triangle  Hamster  Costa Rica   

   ...      nom_9 ord_0        ord_1     ord_2 ord_3 ord_4  ord_5  day month  \
0  ...  02e7c8990   3.0  Contributor       Hot     c     U     Pw  6.0   3.0   
1  ...  f37df64af   3.0  Grandmaster      Warm     e     X     pE  7.0   7.0   
2  ...        NaN   3.0          NaN  Freezing     n     P     eN  5.0   9.0   
3  ...  f9d456e57   1.0       Novice  Lava Hot     a     C    NaN  3.0   3.0   
4  ...  c5361037c   3.0  Grandmaster      Cold     h     C     OZ  5.0  12.0   

  target  
0      0  
1      0  
2      0  
3      0  
4      0  

[5 rows x 25 columns]

In [5]:
df.shape

(600000, 25)

In [6]:
df.describe()

id          bin_0          bin_1          bin_2  \
count  600000.000000  582106.000000  581997.000000  582070.000000   
mean   299999.500000       0.092301       0.185532       0.278704   
std    173205.225094       0.289451       0.388729       0.448362   
min         0.000000       0.000000       0.000000       0.000000   
25%    149999.750000       0.000000       0.000000       0.000000   
50%    299999.500000       0.000000       0.000000       0.000000   
75%    449999.250000       0.000000       0.000000       1.000000   
max    599999.000000       1.000000       1.000000       1.000000   

               ord_0            day          month         target  
count  581712.000000  582048.000000  582012.000000  600000.000000  
mean        1.948224       4.112767       6.371317       0.187205  
std         0.853904       2.034430       3.458959       0.390076  
min         1.000000       1.000000       1.000000       0.000000  
25%         1.000000       2.000000       3.000000       0.000000  
50%         2.000000       5.000000       6.000000       0.000000  
75%         3.000000       6.000000       8.000000       0.000000  
max         3.000000       7.000000      12.000000       1.000000

In [7]:
df.dtypes

id          int64
bin_0     float64
bin_1     float64
bin_2     float64
bin_3      object
bin_4      object
nom_0      object
nom_1      object
nom_2      object
nom_3      object
nom_4      object
nom_5      object
nom_6      object
nom_7      object
nom_8      object
nom_9      object
ord_0     float64
ord_1      object
ord_2      object
ord_3      object
ord_4      object
ord_5      object
day       float64
month     float64
target      int64
dtype: object

In [14]:
#analyse categorical data

In [16]:
df['ord_2'].unique()

array(['Hot', 'Warm', 'Freezing', 'Lava Hot', 'Cold', 'Boiling Hot', nan],
      dtype=object)

In [18]:
mapping = {
    "Freezing": 0,
    "Warm": 1,
    "Hot":2,
    "Boiling Hot":3,
    "Hot": 4,
    "Lava Hot": 5
}

In [1]:
#encoding in a simple format
df.loc[:, 'ord_2'] = df.ord_2.map(mapping)

NameError: name 'df' is not defined

In [23]:
df.ord_2.value_counts()

0.0     142726
1.0     124239
NONE    115897
3.0      84790
4.0      67508
5.0      64840
Name: ord_2, dtype: int64

In [8]:
 #label encoding
 from sklearn import preprocessing
 df.loc[:, "ord_2"] = df.ord_2.fillna("NONE")

In [9]:
lbl_enc = preprocessing.LabelEncoder()

In [10]:
df.loc[:, "ord_2"] = lbl_enc.fit_transform(df.ord_2.values)

In [11]:
#ord_2 has become a integer
df.dtypes

id          int64
bin_0     float64
bin_1     float64
bin_2     float64
bin_3      object
bin_4      object
nom_0      object
nom_1      object
nom_2      object
nom_3      object
nom_4      object
nom_5      object
nom_6      object
nom_7      object
nom_8      object
nom_9      object
ord_0     float64
ord_1      object
ord_2       int64
ord_3      object
ord_4      object
ord_5      object
day       float64
month     float64
target      int64
dtype: object

In [12]:
df.ord_2.unique()

array([3, 6, 2, 4, 1, 0, 5])

In [14]:
example = np.array([
    [2,3,4],
    [5,6,7],
    [8,9,1]
])

print("Size of array: ", example.nbytes)

Size of array:  72


In [23]:
df.ord_2.shape

(600000,)

In [21]:
df[df.ord_2 == "Boiling Hot"].shape

(84790, 25)

In [25]:
df.groupby(["ord_1"])["id"].count()

ord_1
Contributor    109821
Expert         139677
Grandmaster     95866
Master          75998
Novice         160597
Name: id, dtype: int64

In [24]:
#number of rows for each category in the ord_2 row
df.groupby(["ord_2"])["id"].count()

ord_2
Boiling Hot     84790
Cold            97822
Freezing       142726
Hot             67508
Lava Hot        64840
Warm           124239
Name: id, dtype: int64

In [26]:
#transform column categories to count
df.groupby(["ord_2"])["id"].transform("count")

0          67508.0
1         124239.0
2         142726.0
3          64840.0
4          97822.0
            ...   
599995    142726.0
599996     84790.0
599997    142726.0
599998    124239.0
599999     84790.0
Name: id, Length: 600000, dtype: float64

In [29]:
df.groupby(["ord_1", "ord_2"])["id"].count().reset_index(name="count")

ord_1        ord_2  count
0   Contributor  Boiling Hot  15634
1   Contributor         Cold  17734
2   Contributor     Freezing  26082
3   Contributor          Hot  12428
4   Contributor     Lava Hot  11919
5   Contributor         Warm  22774
6        Expert  Boiling Hot  19477
7        Expert         Cold  22956
8        Expert     Freezing  33249
9        Expert          Hot  15792
10       Expert     Lava Hot  15078
11       Expert         Warm  28900
12  Grandmaster  Boiling Hot  13623
13  Grandmaster         Cold  15464
14  Grandmaster     Freezing  22818
15  Grandmaster          Hot  10805
16  Grandmaster     Lava Hot  10363
17  Grandmaster         Warm  19899
18       Master  Boiling Hot  10800
19       Master         Cold  12364
20       Master     Freezing  18035
21       Master          Hot   8594
22       Master     Lava Hot   8209
23       Master         Warm  15734
24       Novice  Boiling Hot  22718
25       Novice         Cold  26271
26       Novice     Freezing  38233
27       Novice          Hot  17850
28       Novice     Lava Hot  17373
29       Novice         Warm  33263

Tips for categorical variables

In [30]:
#fill the nan values
#convert them into integers with label encoding (check ../src/encoding.py)
#then one hot encode them (../src/encoding.py)

In [31]:
df.ord_2.value_counts()

Freezing       142726
Warm           124239
Cold            97822
Boiling Hot     84790
Hot             67508
Lava Hot        64840
Name: ord_2, dtype: int64

In [35]:
df.ord_2.isna().sum()

18075

In [34]:
df.ord_2.value_counts()

Freezing       142726
Warm           124239
Cold            97822
Boiling Hot     84790
Hot             67508
Lava Hot        64840
Name: ord_2, dtype: int64

In [36]:
df.ord_2.fillna("NONE").value_counts()

Freezing       142726
Warm           124239
Cold            97822
Boiling Hot     84790
Hot             67508
Lava Hot        64840
NONE            18075
Name: ord_2, dtype: int64

In [37]:
df.ord_2.isna().sum()

18075

In [38]:
#create new feature
df["new_feature"] = (df.ord_1.astype(str) + "_" + df.ord_2.astype(str))

In [39]:
df.new_feature

0                 Contributor_Hot
1                Grandmaster_Warm
2                    nan_Freezing
3                 Novice_Lava Hot
4                Grandmaster_Cold
                   ...           
599995            Novice_Freezing
599996         Novice_Boiling Hot
599997       Contributor_Freezing
599998                Master_Warm
599999    Contributor_Boiling Hot
Name: new_feature, Length: 600000, dtype: object

In [40]:
df.target.value_counts()

0    487677
1    112323
Name: target, dtype: int64

Dealing with rare values

In [41]:
#we can combine our train and test sets,
# apply cross validation to ensure the train set learns from some the rare variables only in the test set
# then train the model

In [42]:
train = pd.read_csv("../input/train.csv")
test = pd.read_csv("../input/test.csv")

In [43]:
#create a fake rare column
test.loc[:, "target"] = -1

In [45]:
test.target.unique()

array([-1])

In [46]:
data = pd.concat([train, test]).reset_index(drop=True)

In [48]:
#create key features of interest
features = [i for i in train.columns if i not in ["id", "target"]]

In [53]:
for feature in features:
    #instance label encoder encoder
    lbl_encoder = preprocessing.LabelEncoder()
    #since its categorical values, we fillna with str data type
    temp_col = data[feature].fillna("NONE").astype(str).values
    #now encode
    data.loc[:, feature] = lbl_encoder.fit_transform(temp_col)

In [54]:
#split train and test again
train = data[data.target != -1].reset_index(drop=True)
test = data[data.target == -1].reset_index(drop=True)


In [55]:
train.target.unique()

array([0, 1])

In [56]:
test.target.unique()

array([-1])

Model building eda

In [57]:
df_fold = pd.read_csv("../input/train_folds.csv")
df_fold.head()

id  bin_0  bin_1  bin_2 bin_3 bin_4  nom_0      nom_1    nom_2  \
0   26121    0.0    NaN    0.0     F     Y    Red  Trapezoid     Lion   
1  160123    0.0    0.0    1.0     F     N   Blue     Square  Axolotl   
2  449100    0.0    0.0    0.0     F     Y  Green    Polygon     Lion   
3  594368    0.0    1.0    1.0     T     N    Red   Triangle  Axolotl   
4  376157    0.0    0.0    0.0     F     Y   Blue  Trapezoid  Axolotl   

        nom_3  ... ord_0        ord_1 ord_2 ord_3 ord_4 ord_5  day month  \
0     Finland  ...   2.0       Novice  Warm     c   NaN    JT  4.0   3.0   
1       India  ...   1.0       Novice   Hot     k     E    cY  7.0  11.0   
2  Costa Rica  ...   1.0       Expert  Cold     c     F    qN  1.0  12.0   
3     Finland  ...   3.0  Contributor  Warm     m     M    qN  7.0   2.0   
4  Costa Rica  ...   2.0       Master  Cold     e     B    lS  1.0   5.0   

  target kfold  
0      0     0  
1      0     0  
2      0     0  
3      0     0  
4      1     0  

[5 rows x 26 columns]

In [58]:
df_fold.kfold.unique()

array([0, 1, 2, 3, 4])

In [59]:
df_fold.kfold.value_counts()

0    120000
1    120000
2    120000
3    120000
4    120000
Name: kfold, dtype: int64

In [61]:
#target distribution per fold
df_fold[df_fold.kfold == 0].target.value_counts()

0    97536
1    22464
Name: target, dtype: int64

In [62]:
df_fold[df_fold.kfold == 1].target.value_counts()

0    97536
1    22464
Name: target, dtype: int64

In [63]:
df_fold[df_fold.kfold == 2].target.value_counts()

0    97535
1    22465
Name: target, dtype: int64

In [64]:
df_fold[df_fold.kfold == 3].target.value_counts()

0    97535
1    22465
Name: target, dtype: int64

In [65]:
df_fold[df_fold.kfold == 4].target.value_counts()

0    97535
1    22465
Name: target, dtype: int64

In [ ]:
#model building time = ohe_logres.py